import '../DoriosLib/index.js'

import './stats_manager.js'
import './update_stats.js'
import './active_abilities.js'
import './loot_injector.js'
import './belt_abilities.js'
import './doll_abilities.js'
import './face_abilities.js'
import './hat_abilities.js'
import './feet_abilities.js'
import './archaic_charm_abilities.js'
import './amulet_abilities.js'
import './talisman_abilities.js'
import './accessory_abilities.js'
import './relic_abilities.js'
import './underused_relic_abilities.js'
