import { STATSCORE_ICONS } from "../icons.js";

export const REFINING_TABLE_CONFIG = {
    defaults: {
        idleEnergyCost: 100,
        xpTankCapacity: 512000,
        xpFluidType: "xp",
        unlockCatalystId: "utilitycraft:runic_core",
        advancedUnlockCatalystId: "utilitycraft:advanced_runic_core",
        maxIngotsPerRoll: 8,
        advancedMaxIngotsPerRoll: 12,
        advancedStrongMultiplier: 1.35,
        advancedDirectDamageCap: 18,
        strongThreshold: 0.55,
        masterworkThreshold: 0.78,
        transcendentThreshold: 0.92,
        minRollSpread: 0.3,
    },
    chips: new Map([
        ["utilitycraft:chip", { id: "utilitycraft:chip", label: "Chip", minQuality: 0.08, maxQuality: 0.38, baseXpCost: 80, baseEnergyCost: 5200 }],
        ["utilitycraft:basic_chip", { id: "utilitycraft:basic_chip", label: "Basic Chip", minQuality: 0.18, maxQuality: 0.48, baseXpCost: 120, baseEnergyCost: 7600 }],
        ["utilitycraft:advanced_chip", { id: "utilitycraft:advanced_chip", label: "Advanced Chip", minQuality: 0.30, maxQuality: 0.62, baseXpCost: 180, baseEnergyCost: 10800 }],
        ["utilitycraft:expert_chip", { id: "utilitycraft:expert_chip", label: "Expert Chip", minQuality: 0.42, maxQuality: 0.74, baseXpCost: 260, baseEnergyCost: 15400 }],
        ["utilitycraft:ultimate_chip", { id: "utilitycraft:ultimate_chip", label: "Ultimate Chip", minQuality: 0.54, maxQuality: 0.90, baseXpCost: 360, baseEnergyCost: 21200 }],
        ["utilitycraft:superior_chip", { id: "utilitycraft:superior_chip", label: "Superior Chip", minQuality: 0.70, maxQuality: 1, baseXpCost: 500, baseEnergyCost: 28600 }],
        ["utilitycraft:absolute_chip", { id: "utilitycraft:absolute_chip", label: "Absolute Chip", minQuality: 0.90, maxQuality: 1, baseXpCost: 680, baseEnergyCost: 36800 }],
    ]),
    ingots: new Map([
        ["minecraft:copper_ingot", { id: "minecraft:copper_ingot", label: "Copper Ingot", power: 0.2 }],
        ["minecraft:iron_ingot", { id: "minecraft:iron_ingot", label: "Iron Ingot", power: 0.5 }],
        ["minecraft:gold_ingot", { id: "minecraft:gold_ingot", label: "Gold Ingot", power: 0.6 }],
        ["utilitycraft:steel_ingot", { id: "utilitycraft:steel_ingot", label: "Steel Ingot", power: 1 }],
        ["utilitycraft:energized_iron_ingot", { id: "utilitycraft:energized_iron_ingot", label: "Energized Iron Ingot", power: 2 }],
        ["minecraft:diamond", { id: "minecraft:diamond", label: "Diamond", power: 2.75 }],
        ["utilitycraft:titanium", { id: "utilitycraft:titanium", label: "Titanium Ingot", power: 3 }],
        ["minecraft:netherite_ingot", { id: "minecraft:netherite_ingot", label: "Netherite Ingot", power: 4 }],
        ["utilitycraft:aetherium", { id: "utilitycraft:aetherium", label: "Aetherium Ingot", power: 5 }],
    ]),
    templates: {
        weapon: {
            damageMultiplier: 0.10,
            extraDamage: 1.6,
            critChance: 0.05,
            critDamageBonus: 0.24,
            penetration: 0.06,
            lifesteal: 0.018,
            elementalChance: 0.24,
            elementalDamage: 3.2,
        },
        tool: {
            extraDamage: 0.8,
            bonusLootChance: 0.18,
            durabilitySaveChance: 0.08,
            elementalChance: 0.10,
            elementalDamage: 1.4,
        },
        hybrid: {
            damageMultiplier: 0.08,
            extraDamage: 1.25,
            critChance: 0.035,
            critDamageBonus: 0.5,
            penetration: 0.05,
            lifesteal: 0.025,
            bonusLootChance: 0.20,
            durabilitySaveChance: 0.20,
            elementalChance: 0.30,
            elementalDamage: 4,
        },
        support: {
            damageReduction: 0.025,
            durabilityPreserveChance: 0.10,
            negateAllDamageChance: 0.001,
            elementalChance: 0.12,
        },
        utility: {
            extraDamage: 0.4,
            bonusLootChance: 0.12,
            durabilitySaveChance: 0.12,
            elementalChance: 0.06,
            elementalDamage: 0.8,
        },
    },
    tierScales: {
        wood: 0.2,
        stone: 0.5,
        copper: 0.45,
        iron: 0.6,
        steel: 0.8,
        golden: 0.75,
        diamond: 0.9,
        netherite: 1.01,
        titanium: 0.98,
        aetherium: 1,
    },
    elements: [
        { id: "plant", label: `\u00A7a${STATSCORE_ICONS.plant} Plant`, weight: 22, damageScale: 0.05, durationTicks: 120, amplifier: 0 },
        { id: "frost", label: `\u00A7b${STATSCORE_ICONS.ice} Frost`, weight: 20, damageScale: 0.07, durationTicks: 90, amplifier: 1 },
        { id: "fire", label: `\u00A7c${STATSCORE_ICONS.fire} Fire`, weight: 20, damageScale: 0.08, seconds: 4 },
        { id: "lightning", label: `\u00A7e${STATSCORE_ICONS.lightning} Lightning`, weight: 18, damageScale: 0.09, durationTicks: 60, amplifier: 0 },
        { id: "darkness", label: `\u00A78${STATSCORE_ICONS.darkness} Darkness`, weight: 20, damageScale: 0.07, durationTicks: 100, amplifier: 0 },
        { id: "light", label: `\u00A7e${STATSCORE_ICONS.holy} Blessing`, weight: 18, blessingDamage: 8, healAmount: 8, tickInterval: 10, mobDurationTicks: 18000, playerDurationTicks: 2400 },
        { id: "wind", label: `\u00A7f${STATSCORE_ICONS.wind} Wind`, weight: 9, damageScale: 0.055, durationTicks: 100 },
        { id: "water", label: `\u00A79${STATSCORE_ICONS.water} Water`, weight: 11, damageScale: 0.06, durationTicks: 100 },
        { id: "void", label: `\u00A75${STATSCORE_ICONS.void} Void`, weight: 2, damageScale: 0.08, durationTicks: 120, coreRequirement: "advanced", allowedTypes: ["weapon", "tool", "hybrid", "utility"] },
        { id: "earth", label: `\u00A76${STATSCORE_ICONS.earth} Earth`, weight: 8, damageScale: 0, coreRequirement: "runic", allowedTypes: ["support"] },
    ],
};
